/* =====================================================================
   MaStartup AI - Export engine (NovaExport)
   PDF  -> window.print() to a clean print stylesheet (no deps, reliable)
           or jsPDF if available.
   DOCX -> generated as a Word-compatible HTML document (.doc) which Word
           and Google Docs open natively. Upgradable to the `docx` lib.
   PPTX -> uses PptxGenJS if loaded (CDN); otherwise exports an HTML deck.
   Libraries are loaded lazily from CDN and degrade gracefully offline.
   ===================================================================== */
(function (global) {
  'use strict';

  function download(filename, blob) {
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click();
    setTimeout(function () { document.body.removeChild(a); URL.revokeObjectURL(url); }, 200);
  }

  function loadScript(src) {
    return new Promise(function (resolve, reject) {
      if (document.querySelector('script[data-src="' + src + '"]')) return resolve();
      var s = document.createElement('script');
      s.src = src; s.async = true; s.dataset.src = src;
      s.onload = resolve; s.onerror = function () { reject(new Error('Failed to load ' + src)); };
      document.head.appendChild(s);
    });
  }

  function toast(msg) {
    if (global.novaToast) return global.novaToast(msg);
    console.log('[NovaExport]', msg);
  }

  /* ------------------------------- PDF -------------------------------- */
  // Business plan / generic document -> print-to-PDF using the print CSS.
  function exportPDF(title) {
    var prev = document.title;
    document.title = (title || 'MaStartup') + ' — MaStartup AI';
    toast('Opening print dialog — choose "Save as PDF".');
    window.print();
    setTimeout(function () { document.title = prev; }, 500);
  }

  /* ------------------------------ DOCX -------------------------------- */
  // Produces a Word-compatible document. Word/Google Docs open it natively.
  function exportDOCX(filename, title, sections) {
    var styles =
      'body{font-family:Calibri,Arial,sans-serif;color:#222;line-height:1.5}' +
      'h1{color:#5b3df6;font-size:22pt}h2{color:#3b82f6;font-size:14pt;border-bottom:1px solid #ddd;padding-bottom:4px}' +
      'p,li{font-size:11pt}';
    var body = '<h1>' + esc(title) + '</h1>';
    sections.forEach(function (s) {
      body += '<h2>' + esc(s.heading) + '</h2>';
      body += '<div>' + (s.html || ('<p>' + esc(s.text || '') + '</p>')) + '</div>';
    });
    var html =
      '<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" ' +
      'xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">' +
      '<head><meta charset="utf-8"><title>' + esc(title) + '</title><style>' + styles + '</style></head>' +
      '<body>' + body + '</body></html>';
    download((filename || 'nova-document') + '.doc', new Blob(['\ufeff' + html], { type: 'application/msword' }));
    toast('Word document exported.');
  }

  /* ------------------------------ PPTX -------------------------------- */
  // Uses PptxGenJS from CDN when online; falls back to an HTML deck file.
  async function exportPPTX(filename, title, slides) {
    try {
      if (!global.PptxGenJS) {
        await loadScript('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js');
      }
      var P = global.PptxGenJS;
      var pptx = new P();
      pptx.defineLayout({ name: 'NOVA', width: 13.33, height: 7.5 });
      pptx.layout = 'NOVA';
      pptx.author = 'MaStartup AI';

      // Title slide
      var t = pptx.addSlide();
      t.background = { color: '0D0D1A' };
      t.addText(title, { x: 0.7, y: 2.6, w: 12, h: 1.2, fontSize: 40, bold: true, color: 'FFFFFF', fontFace: 'Arial' });
      t.addText('Investor Pitch Deck · Generated by MaStartup AI', { x: 0.7, y: 3.9, w: 12, fontSize: 16, color: '8B5CF6' });

      slides.forEach(function (s, i) {
        var sl = pptx.addSlide();
        sl.background = { color: i % 2 ? '12121F' : '0D0D1A' };
        sl.addText((i + 1) + '. ' + s.title, { x: 0.7, y: 0.5, w: 12, h: 0.8, fontSize: 26, bold: true, color: 'A78BFA', fontFace: 'Arial' });
        sl.addText(s.body, { x: 0.7, y: 1.7, w: 12, h: 5, fontSize: 18, color: 'E8E8FF', fontFace: 'Arial', valign: 'top', lineSpacingMultiple: 1.3 });
      });

      await pptx.writeFile({ fileName: (filename || 'nova-pitch-deck') + '.pptx' });
      toast('PowerPoint deck exported.');
    } catch (e) {
      console.warn('PPTX export fell back to HTML:', e.message);
      exportDeckHTML(filename, title, slides);
    }
  }

  function exportDeckHTML(filename, title, slides) {
    var s = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' + esc(title) + '</title>' +
      '<style>body{margin:0;font-family:Arial,sans-serif;background:#0d0d1a;color:#fff}' +
      '.slide{height:100vh;display:flex;flex-direction:column;justify-content:center;padding:8%;page-break-after:always;border-bottom:1px solid #222}' +
      'h1{font-size:3rem;color:#a78bfa}h2{font-size:2rem;color:#a78bfa}p{font-size:1.3rem;color:#e8e8ff;line-height:1.6;white-space:pre-line}</style></head><body>';
    s += '<div class="slide"><h1>' + esc(title) + '</h1><p style="color:#8b5cf6">Investor Pitch Deck</p></div>';
    slides.forEach(function (sl, i) { s += '<div class="slide"><h2>' + (i + 1) + '. ' + esc(sl.title) + '</h2><p>' + esc(sl.body) + '</p></div>'; });
    s += '</body></html>';
    download((filename || 'nova-pitch-deck') + '.html', new Blob([s], { type: 'text/html' }));
    toast('Deck exported as HTML (open in browser, print to PPTX/PDF).');
  }

  function esc(t) { return String(t == null ? '' : t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

  global.NovaExport = { exportPDF: exportPDF, exportDOCX: exportDOCX, exportPPTX: exportPPTX };
})(window);
